version: '3.9'

services:
  db-default:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    container_name: pgvector_docker
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django_app
    command: >
      sh -c "
        echo 'Waiting for DB to be ready...';
        until pg_isready -h db-default -U ${DATABASE_USER}; do sleep 1; done;
        echo 'Creating pgvector extension...';
        PGPASSWORD=${DATABASE_PASSWORD} psql -h db-default -U ${DATABASE_USER} -d ${DATABASE_NAME} -c 'CREATE EXTENSION IF NOT EXISTS vector;';
        echo 'Running migrations...';
        python manage.py migrate;
        echo 'Starting Django...';
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db-default
    env_file:
      - .env
    environment:
      - DATABASE_HOST=db-default

volumes:
  postgres_data:
